### ISSUE TITLE
[Suggest]: Support work with windows.

### ISSUE THREAD

**Issue by nonzzz** [zaunist/k#1]
# Background

From [K/pkg/basedir.go](https://github.com/zaunist/k/blob/main/pkg/conf/basedir.go). I think we can use `os.Getenv` replace `user.Current()`. Because `os.GetEnv` can get clean infomation. And we only judge user platform that is 'win' or others.

**Comment by zaunist** [comment]
Thanks for your suggestion. We will update in subsequent iterations.

**Comment by nonzzz** [comment]
I already saw you're refactor the part. I will close this issue.
